/**
 * Quest worlds: the data format for the little tile-map lessons.
 *
 * A quest is a small grid world with a controllable character, objects that can
 * be picked up / put down / acted on, and an ordered list of goals whose
 * instructions are written in imperative Mandarin ("把苹果放在桌子上").
 *
 * The whole world — terrain, objects, verbs, goals — is generated by Claude and
 * stored as JSON, so nothing here is canned. Everything the engine needs to
 * check whether an instruction has been carried out lives in the world spec as
 * declarative conditions, which is what keeps generated lessons playable
 * without any bespoke code per lesson.
 */

export const QUEST_SCHEMA_VERSION = 1;

export interface QuestText {
  hanzi: string;
  pinyin: string;
  english: string;
}

/** One kind of ground tile. `key` is the single character used in `grid`. */
export interface QuestTerrain {
  key: string;
  hanzi: string;
  pinyin: string;
  english: string;
  /** CSS colour for the tile. */
  color: string;
  /** Optional faint decoration drawn on the tile (single emoji). */
  emoji?: string | null;
  walkable: boolean;
}

/** A state an object can be in, e.g. 开着 / 关着. */
export interface QuestObjectState {
  id: string;
  hanzi: string;
  pinyin: string;
  english: string;
  /** Overrides the object's emoji while in this state. */
  emoji?: string | null;
  /** Overrides the object's blocks_movement while in this state. */
  blocks_movement?: boolean | null;
}

/** A verb the learner can apply to an object — this is the imperative vocabulary. */
export interface QuestObjectAction {
  id: string;
  /** The verb as an imperative, e.g. 打开. */
  hanzi: string;
  pinyin: string;
  english: string;
  /** Only offered while the object is in this state. */
  requires_state?: string | null;
  /** Only offered while the player is carrying this object. */
  requires_holding?: string | null;
  /** State the object moves to when the action is performed. */
  sets_state?: string | null;
  /** Object disappears when the action is performed (吃, 喝 …). */
  removes_object?: boolean | null;
}

export interface QuestObject {
  id: string;
  /** Single emoji used as the sprite. */
  emoji: string;
  hanzi: string;
  pinyin: string;
  english: string;
  x: number;
  y: number;
  /** Can be picked up and carried. */
  portable: boolean;
  /** Things can be put on / in it — targets of `object_on` conditions. */
  surface: boolean;
  /** Cannot be walked through (walls, closed doors). */
  blocks_movement: boolean;
  states?: QuestObjectState[] | null;
  initial_state?: string | null;
  actions?: QuestObjectAction[] | null;
  /**
   * Hidden until another object reaches a state — milk inside a closed fridge.
   * Once revealed it stays revealed.
   */
  hidden_until?: { object: string; state: string } | null;
}

export type QuestCondition =
  /** The player is carrying the object. */
  | { type: 'holding'; object: string }
  /** The player is not carrying the object (it has been put down somewhere). */
  | { type: 'not_holding'; object: string }
  /** The object sits on a specific tile. */
  | { type: 'object_at'; object: string; x: number; y: number }
  /** The object has been put down on/in another object (same tile). */
  | { type: 'object_on'; object: string; target: string }
  /** The object has been put down on a kind of ground tile. */
  | { type: 'object_on_terrain'; object: string; terrain: string }
  /** The player stands on a specific tile. */
  | { type: 'player_at'; x: number; y: number }
  /** The player stands on a kind of ground tile. */
  | { type: 'player_on_terrain'; terrain: string }
  /** The player stands on or beside the object. */
  | { type: 'player_next_to'; object: string }
  /** The object is in a given state. */
  | { type: 'object_state'; object: string; state: string }
  /** The object is gone (eaten, drunk, used up). */
  | { type: 'object_removed'; object: string }
  /** The action has been performed on the object at least once. */
  | { type: 'performed'; object: string; action: string }
  | { type: 'all_of'; conditions: QuestCondition[] }
  | { type: 'any_of'; conditions: QuestCondition[] }
  /** Each condition must become true in order — this is what makes 先…然后… work. */
  | { type: 'sequence'; conditions: QuestCondition[] };

export interface QuestGoal {
  id: string;
  /** The instruction, in imperative Mandarin. */
  instruction: QuestText;
  /** Shown when the learner asks for help. */
  hint?: QuestText | null;
  /** Shown when the goal is completed. */
  success?: QuestText | null;
  condition: QuestCondition;
}

export type QuestGlossaryPos = 'verb' | 'noun' | 'phrase' | 'other';

export interface QuestGlossaryEntry extends QuestText {
  pos: QuestGlossaryPos;
  /** Short note on usage or register, e.g. "把 + object + 放在 + place + 上". */
  note?: string | null;
}

export interface QuestWorld {
  schema_version: number;
  title: QuestText;
  /** One or two sentences of setup, in Chinese. */
  scenario: QuestText;
  width: number;
  height: number;
  terrain: QuestTerrain[];
  /** `height` rows of `width` terrain keys. */
  grid: string[];
  player: { emoji: string; x: number; y: number };
  /** How many objects can be carried at once. */
  carry_limit: number;
  objects: QuestObject[];
  /** Goals are played in order. */
  goals: QuestGoal[];
  glossary: QuestGlossaryEntry[];
}

/** Persisted quest record (a generated world plus its progress). */
export interface Quest {
  id: string;
  user_id: string;
  title: string;
  topic: string | null;
  status: 'generating' | 'ready' | 'error';
  world: QuestWorld | null;
  error: string | null;
  completed_at: string | null;
  best_moves: number | null;
  play_count: number;
  created_at: string;
}

/** List rows leave the (large) world JSON out. */
export type QuestSummary = Omit<Quest, 'world'> & {
  goal_count: number;
  object_count: number;
};
