import { test, expect, APIRequestContext } from '@playwright/test';

/**
 * 成语 Idioms (beta; docs/IDIOMS.md): More → Practice → the list → 画蛇添足 (generated by the
 * E2E stand-in for Claude, worker/src/services/idioms-fake.ts) → the story with its source,
 * English on demand → the "Try it" check → + Add as card (the card-standard fields, into the
 * user's deck) → the card tie-in says it's in the deck. A typo is "not a 成语 — did you mean".
 */

const API = process.env.E2E_API_URL || 'http://localhost:8787';

async function api<T = unknown>(request: APIRequestContext, path: string, opts: { method?: 'GET' | 'POST'; token?: string; data?: unknown } = {}): Promise<T> {
  const res = await request.fetch(`${API}${path}`, {
    method: opts.method ?? 'GET',
    headers: { 'content-type': 'application/json', ...(opts.token ? { Authorization: `Bearer ${opts.token}` } : {}) },
    data: opts.data === undefined ? undefined : JSON.stringify(opts.data),
  });
  if (!res.ok()) throw new Error(`${opts.method ?? 'GET'} ${path} → ${res.status()} ${(await res.text()).slice(0, 200)}`);
  return (await res.json()) as T;
}

test('idioms: list → 画蛇添足 → story → try it → add as card; a typo suggests the idiom', async ({ page, request }) => {
  test.setTimeout(120_000);
  const email = `idioms-${Date.now()}-${Math.floor(Math.random() * 1e6)}@test.e2e`;
  const { user, session_token: token } = await api<{ user: { id: string }; session_token: string }>(request, '/api/test/auth', { method: 'POST', data: { email, name: 'Jerome' } });
  expect(user.id).toBeTruthy();
  const deck = await api<{ id: string }>(request, '/api/decks', { method: 'POST', token, data: { name: '成语 deck' } });

  await page.goto(`/?session_token=${token}`);
  await page.waitForLoadState('networkidle');
  await page.goto('/more');
  await page.getByRole('link', { name: /成语 Idioms \(beta\)/ }).click();
  await expect(page).toHaveURL(/\/idioms$/);
  await expect(page.getByTestId('idioms-page')).toContainText('With a story');

  await page.getByTestId('idiom-tile').filter({ hasText: '画蛇添足' }).click();
  await expect(page.getByTestId('idiom-hanzi')).toHaveText('画蛇添足', { timeout: 30_000 });
  await expect(page.getByTestId('idiom-page')).toContainText('huà shé tiān zú');
  await expect(page.getByTestId('idiom-source')).toContainText('《战国策·齐策二》');

  // The story reads in Chinese first; English comes on demand.
  const story = page.getByTestId('idiom-story');
  await expect(story).toContainText('楚国有一个人请客人喝酒');
  await expect(story.getByTestId('idiom-para-en')).toHaveCount(0);
  await page.getByTestId('idiom-toggle-english').click();
  await expect(story.getByTestId('idiom-para-en').first()).toContainText('state of Chu');

  // Examples start blank: a tap uncovers the Chinese.
  const example = page.getByTestId('idiom-example').first();
  await expect(example).toContainText('listen, then tap to reveal');
  await example.getByRole('button', { name: 'Reveal example 1' }).click();
  await expect(example).toContainText('别画蛇添足');

  // Try it: answer both questions.
  const questions = page.getByTestId('idiom-quiz-question');
  await questions.nth(0).getByRole('button', { name: /ruin something by adding/ }).click();
  await expect(questions.nth(0)).toContainText('✓ Right.');
  await questions.nth(1).getByRole('button', { name: /我今天画蛇添足地去上班了/ }).click();
  await expect(questions.nth(1)).toContainText('✗ Not quite.');
  await expect(page.getByTestId('idiom-quiz-score')).toContainText('1 / 2');

  // + Add as card → the deck.
  await page.getByTestId('idiom-add-card').click();
  const dialog = page.getByRole('dialog', { name: 'Add 画蛇添足 as a card' });
  await expect(dialog).toBeVisible();
  await dialog.getByRole('button', { name: 'Add to deck' }).click();
  await expect(page.getByTestId('idiom-card-footer')).toContainText('✓ Added', { timeout: 15_000 });
  const saved = await api<{ notes: Array<{ hanzi: string; fun_facts: string | null; sentence_clue: string | null }> }>(request, `/api/decks/${deck.id}`, { token });
  const note = saved.notes.find((n) => n.hanzi === '画蛇添足');
  expect(note?.fun_facts).toContain('Origin: 《战国策·齐策二》');
  expect(note?.sentence_clue).toBe('这句话已经很好了，别画蛇添足。');

  // A typo: not a 成语 — did you mean 画蛇添足?
  await page.goto('/idioms');
  await page.getByLabel('Look up any 成语').fill('画蛇添脚');
  await page.getByRole('button', { name: 'Look up' }).click();
  await expect(page.getByTestId('idiom-state-not_idiom')).toContainText('Did you mean', { timeout: 30_000 });
  await page.getByRole('link', { name: '画蛇添足' }).click();
  await expect(page.getByTestId('idiom-hanzi')).toHaveText('画蛇添足', { timeout: 30_000 });
});
