package dev.jeromeswannack.chineselearning.lab.data.audiolessons

import android.content.Context
import androidx.annotation.OptIn
import androidx.media3.common.AudioAttributes
import androidx.media3.common.C
import androidx.media3.common.MediaItem
import androidx.media3.common.Player
import androidx.media3.common.util.UnstableApi
import androidx.media3.datasource.RawResourceDataSource
import androidx.media3.exoplayer.ExoPlayer
import dev.jeromeswannack.chineselearning.lab.R
import dev.jeromeswannack.chineselearning.lab.core.AudioLessonMusic

/*
 * The soft music bed under an audio lesson (docs/AUDIO_LESSONS.md "Music"): the lesson MP3 is
 * speech only, so the player mixes the music in itself — a second, looping player at a low volume,
 * inside the background service next to the lesson's ExoPlayer, so it keeps going with the screen
 * off and stops with the lesson (pause, the end, the sleep timer — which also fades it out).
 * The track is res/raw/lesson_music.mp3, the web's /audio/lesson-music-v1.mp3 (CC0, generated by
 * scripts/audio/generate-lesson-music.mjs), bundled in the APK, so it plays offline.
 */

/** What [LessonMusic] drives: the real one is [ExoMusicTrack]; tests use a fake. */
interface MusicTrack {
    fun play()
    fun pause()
    fun setVolume(volume: Float)
    fun release()
}

/**
 * The rules (`AudioLessonMusic`, parity-tested with the web): plays only while the lesson plays
 * and the music is on; its volume = the learner's music volume × the sleep timer's fade.
 * Main thread only.
 */
class LessonMusic(private val track: MusicTrack) {
    var on: Boolean = false
        private set
    var volume: Double = AudioLessonMusic.DEFAULT_VOLUME
        private set

    /** Whether the track has been told to play (and not paused since). */
    var playing: Boolean = false
        private set

    private var lessonPlaying = false
    private var fade = 1.0
    private var lastVolume = -1f

    fun setOn(value: Boolean) {
        on = value
        apply()
    }

    fun setVolume(value: Double) {
        volume = AudioLessonMusic.parseVolume(value)
        apply()
    }

    /** Called by the engine whenever the lesson starts / stops playing and on every tick (the fade). */
    fun update(lessonPlaying: Boolean, fade: Double = 1.0) {
        this.lessonPlaying = lessonPlaying
        this.fade = fade
        apply()
    }

    private fun apply() {
        val v = AudioLessonMusic.outputVolume(volume, fade).toFloat()
        if (v != lastVolume) {
            lastVolume = v
            track.setVolume(v)
        }
        val play = AudioLessonMusic.shouldPlay(on, lessonPlaying)
        if (play && !playing) {
            playing = true
            track.play()
        } else if (!play && playing) {
            playing = false
            track.pause()
        }
    }

    fun release() {
        if (playing) track.pause()
        playing = false
        track.release()
    }
}

/** The bundled loop in its own ExoPlayer: repeat one, no audio focus of its own (the lesson's player holds it). */
@OptIn(UnstableApi::class)
class ExoMusicTrack(private val context: Context) : MusicTrack {
    private var player: ExoPlayer? = null
    private var volume = AudioLessonMusic.DEFAULT_VOLUME.toFloat()

    private fun player(): ExoPlayer = player ?: ExoPlayer.Builder(context)
        .setAudioAttributes(AudioAttributes.Builder().setUsage(C.USAGE_MEDIA).setContentType(C.AUDIO_CONTENT_TYPE_MUSIC).build(), /* handleAudioFocus = */ false)
        .build()
        .also { p ->
            p.setMediaItem(MediaItem.fromUri(RawResourceDataSource.buildRawResourceUri(R.raw.lesson_music)))
            p.repeatMode = Player.REPEAT_MODE_ONE
            p.volume = volume
            p.prepare()
            player = p
        }

    override fun play() {
        player().play()
    }

    override fun pause() {
        player?.pause()
    }

    override fun setVolume(volume: Float) {
        this.volume = volume
        player?.volume = volume
    }

    override fun release() {
        player?.release()
        player = null
    }
}
