package dev.jeromeswannack.chineselearning.lab.core

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.boolean
import kotlinx.serialization.json.double
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.long
import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.fail

/**
 * The Kotlin port must reproduce the web app's TypeScript exactly. Fixtures are
 * generated by android-lab/parity/generate-fixtures.ts (Gradle runs it before
 * the tests). Doubles are compared for EXACT equality: they go through the same
 * operations in the same order, and any drift means scheduling would diverge.
 */
class ParityTest {
    private fun fixture(name: String): JsonObject {
        val dir = System.getProperty("parity.dir") ?: fail("parity.dir not set — run through Gradle")
        return Json.parseToJsonElement(File(dir, name).readText()).jsonObject
    }

    private val JsonElement.str: String? get() = if (this is JsonNull) null else jsonPrimitive.content
    private val JsonElement.longOrNull: Long? get() = if (this is JsonNull) null else jsonPrimitive.long

    private fun assertState(expected: JsonObject, actual: ComputedCardState, where: String) {
        assertEquals(expected["queue"]!!.jsonPrimitive.int, actual.queue, "$where queue")
        assertEquals(expected["stability"]!!.jsonPrimitive.double, actual.stability, "$where stability")
        assertEquals(expected["difficulty"]!!.jsonPrimitive.double, actual.difficulty, "$where difficulty")
        assertEquals(expected["scheduled_days"]!!.jsonPrimitive.long, actual.scheduledDays, "$where scheduled_days")
        assertEquals(expected["reps"]!!.jsonPrimitive.int, actual.reps, "$where reps")
        assertEquals(expected["lapses"]!!.jsonPrimitive.int, actual.lapses, "$where lapses")
        assertEquals(expected["next_review_at"]!!.str, actual.nextReviewAt, "$where next_review_at")
        assertEquals(expected["due_timestamp"]!!.longOrNull, actual.dueTimestamp, "$where due_timestamp")
        assertEquals(expected["last_reviewed_at"]!!.str, actual.lastReviewedAt, "$where last_reviewed_at")
        assertEquals(expected["ease_factor"]!!.jsonPrimitive.double, actual.easeFactor, "$where ease_factor")
        assertEquals(expected["interval"]!!.jsonPrimitive.long, actual.interval, "$where interval")
        assertEquals(expected["repetitions"]!!.jsonPrimitive.int, actual.repetitions, "$where repetitions")
        assertEquals(expected["learning_step"]!!.jsonPrimitive.int, actual.learningStep, "$where learning_step")
    }

    @Test
    fun fsrsReplayApplyPreviewsAndRetrievabilityMatchTypeScript() {
        val sequences = fixture("fsrs.json")["sequences"]!!.jsonArray
        var checked = 0
        for (seq in sequences) {
            val cardId = seq.jsonObject["card_id"]!!.str!!
            val events = mutableListOf<ReviewEventInput>()
            var state = CardScheduler.initialCardState()
            seq.jsonObject["steps"]!!.jsonArray.forEachIndexed { i, stepEl ->
                val step = stepEl.jsonObject
                val rating = step["rating"]!!.jsonPrimitive.int
                val reviewedAt = step["reviewed_at"]!!.str!!
                val where = "$cardId step $i"
                val applied = CardScheduler.applyReview(state, rating, reviewedAt)
                assertState(step["applied"]!!.jsonObject, applied, "$where applyReview")
                events += ReviewEventInput("$cardId-e$i", cardId, rating, reviewedAt)
                val replayed = CardScheduler.computeCardState(events)
                assertState(step["replayed"]!!.jsonObject, replayed, "$where computeCardState")

                val previewAt = step["preview_at"]!!.jsonPrimitive.long
                val previews = CardScheduler.intervalPreviews(replayed, previewAt)
                step["previews"]!!.jsonArray.forEachIndexed { r, pEl ->
                    val p = pEl.jsonObject
                    assertEquals(p["intervalText"]!!.str, previews[r].intervalText, "$where preview $r text")
                    assertEquals(p["intervalDays"]!!.jsonPrimitive.double, previews[r].intervalDays, "$where preview $r days")
                    assertEquals(p["nextState"]!!.jsonPrimitive.int, previews[r].nextState, "$where preview $r state")
                }
                assertEquals(step["retrievability"]!!.jsonPrimitive.double, CardScheduler.retrievability(replayed, previewAt), "$where retrievability")
                state = replayed
                checked++
            }
        }
        println("FSRS parity: $checked review steps across ${sequences.size} cards")
    }

    @Test
    fun formatIntervalMatchesTypeScript() {
        for (el in fixture("format-interval.json")["intervals"]!!.jsonArray) {
            val o = el.jsonObject
            val minutes = o["minutes"]!!.jsonPrimitive.double
            assertEquals(o["text"]!!.str, CardScheduler.formatInterval(minutes), "formatInterval($minutes)")
            assertEquals(o["lessThan"]!!.str, CardScheduler.formatInterval(minutes, true), "formatInterval($minutes, true)")
        }
    }

    @Test
    fun budgetAllocatorMatchesTypeScript() {
        for ((i, el) in fixture("budget.json")["cases"]!!.jsonArray.withIndex()) {
            val o = el.jsonObject
            val pools = o["pools"]!!.jsonArray.map {
                val p = it.jsonObject
                DeckNewPool(
                    deckId = p["deckId"]!!.str!!,
                    priority = p["priority"]!!.jsonPrimitive.int,
                    createdAt = p["createdAt"]!!.str!!,
                    totalNew = p["totalNew"]!!.jsonPrimitive.int,
                    totalSecondaryNew = p["totalSecondaryNew"]!!.jsonPrimitive.int,
                    capPrimary = p["capPrimary"]!!.jsonPrimitive.int,
                    capSecondary = p["capSecondary"]!!.jsonPrimitive.int,
                    studiedPrimary = p["studiedPrimary"]!!.jsonPrimitive.int,
                    studiedSecondary = p["studiedSecondary"]!!.jsonPrimitive.int,
                )
            }
            val b = o["budget"]!!.jsonObject
            val budget = StudyBudget(b["new_cards_per_day"]!!.jsonPrimitive.int, b["secondary_cards_per_day"]!!.jsonPrimitive.int)
            val s = o["spentElsewhere"]!!.jsonObject
            val alloc = Budget.allocateNewCards(pools, budget, o["bonus"]!!.jsonPrimitive.int, Spent(s["primary"]!!.jsonPrimitive.int, s["secondary"]!!.jsonPrimitive.int))
            assertEquals(o["order"]!!.jsonArray.map { it.str }, Budget.sortForQueue(pools, { it.priority }, { it.createdAt }).map { it.deckId }, "case $i order")
            val expected = o["allocation"]!!.jsonArray.map { val a = it.jsonObject; Triple(a["deckId"]!!.str!!, a["primary"]!!.jsonPrimitive.int, a["secondary"]!!.jsonPrimitive.int) }
            assertEquals(expected, alloc.entries.map { Triple(it.key, it.value.primary, it.value.secondary) }, "case $i allocation")
            assertEquals(o["daysToIntroduce"]!!.jsonPrimitive.int, Budget.daysToIntroduce(pools[0].totalNew, budget.newCardsPerDay), "case $i days")
        }
    }

    @Test
    fun answerNormalisationMatchesTypeScript() {
        val f = fixture("answers.json")
        for (el in f["answers"]!!.jsonArray) {
            val o = el.jsonObject
            val input = o["input"]!!.str!!
            assertEquals(o["numbers"]!!.str, AnswerKey.normalizeNumbersToHanzi(input), "numbers '$input'")
            assertEquals(o["key"]!!.str, AnswerKey.hanziAnswerKey(input), "key '$input'")
            assertEquals(o["stripped"]!!.str, AnswerKey.stripPunctuation(input), "stripped '$input'")
            assertEquals(o["normalized"]!!.str, AnswerKey.normalize(input), "normalized '$input'")
        }
        for (el in f["ints"]!!.jsonArray) {
            val o = el.jsonObject
            assertEquals(o["hanzi"]!!.str, AnswerKey.intToHanzi(o["n"]!!.jsonPrimitive.long), "intToHanzi")
        }
    }

    @Test
    fun jsNumberSemanticsMatch() {
        for (el in fixture("js-numbers.json")["numbers"]!!.jsonArray) {
            val o = el.jsonObject
            val x = o["x"]!!.jsonPrimitive.double
            assertEquals(o["str"]!!.str, Js.numberToString(x), "String($x)")
            assertEquals(o["fixed8"]!!.jsonPrimitive.double, Js.toFixed8(x), "toFixed8($x)")
            if (Math.abs(x) < 1e21) assertEquals(o["fixed1"]!!.str, Js.toFixed(x, 1), "toFixed($x, 1)")
            assertEquals(o["round"]!!.jsonPrimitive.double, Js.round(x), "Math.round($x)")
        }
    }
}
