package dev.jeromeswannack.chineselearning.lab.data.lessons

import android.util.Base64
import dev.jeromeswannack.chineselearning.lab.Config
import dev.jeromeswannack.chineselearning.lab.data.Api
import dev.jeromeswannack.chineselearning.lab.data.api.practiceTts
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File

/**
 * Offline media for lessons and readers (the web's ttsCache.ts + the blob cache for
 * images): generated TTS clips and R2 images as files, fetched when online and read
 * from disk afterwards — so a prefetched lesson plays on the train.
 */
class LessonMedia(filesDir: File, private val api: Api) {
    private val ttsDir = File(filesDir, "lesson-tts").apply { mkdirs() }
    private val imageDir = File(filesDir, "lesson-images").apply { mkdirs() }

    /** `ttsCacheKey`: djb2 over "text|voice", with the speed. Same key shape as the web. */
    fun ttsKey(text: String, speed: Double = DEFAULT_SPEED, voice: String = DEFAULT_VOICE): String {
        var hash = 5381L
        for (c in "$text|$voice") hash = ((hash shl 5) + hash + c.code) and 0xFFFFFFFFL
        return "tts/${java.lang.Long.toString(hash, 36)}-x${speedText(speed)}"
    }

    private fun speedText(speed: Double) = if (speed == Math.floor(speed)) speed.toLong().toString() else speed.toString()

    private fun fileFor(dir: File, key: String) = File(dir, key.replace(Regex("[^A-Za-z0-9._-]"), "_"))

    /** The cached clip for [key] (see [ttsKey] / reader page keys), or null. */
    fun cachedTts(key: String): File? = fileFor(ttsDir, key).takeIf { it.exists() && it.length() > 0 }

    /**
     * Cache-first TTS (`getTTSWithCache`): the cached clip, else generated by
     * `POST /api/practice/tts` when [online] and stored. Null offline with nothing cached.
     */
    suspend fun tts(text: String, voice: String? = null, speed: Double = DEFAULT_SPEED, key: String = ttsKey(text, speed, voice ?: DEFAULT_VOICE), online: Boolean, regenerate: Boolean = false): File? {
        if (text.isBlank()) return null
        if (!regenerate) cachedTts(key)?.let { return it }
        if (!online) return null
        return try {
            val res = api.practiceTts(text, speed, voice)
            withContext(Dispatchers.IO) {
                val bytes = Base64.decode(res.audioBase64, Base64.DEFAULT)
                val dest = fileFor(ttsDir, key)
                val tmp = File(dest.parentFile, dest.name + ".part")
                tmp.writeBytes(bytes)
                tmp.renameTo(dest)
                dest
            }
        } catch (e: CancellationException) {
            throw e
        } catch (e: Exception) {
            null
        }
    }

    fun cachedImage(key: String?): File? =
        key?.takeIf { it.isNotBlank() }?.let { fileFor(imageDir, it.removePrefix("/api/audio/")) }?.takeIf { it.exists() && it.length() > 0 }

    /** An R2 image (served from /api/audio/<key>, like reader illustrations), downloaded once. */
    suspend fun image(key: String?, online: Boolean): File? {
        if (key.isNullOrBlank()) return null
        cachedImage(key)?.let { return it }
        if (!online) return null
        return try {
            val dest = fileFor(imageDir, key.removePrefix("/api/audio/"))
            api.download(Config.audioUrl(key, api.baseUrl), dest)
            dest
        } catch (e: CancellationException) {
            throw e
        } catch (e: Exception) {
            null
        }
    }

    fun clear() {
        ttsDir.listFiles()?.forEach { it.delete() }
        imageDir.listFiles()?.forEach { it.delete() }
    }

    companion object {
        /** DEFAULT_TTS_SPEED — the app-wide narration speed. */
        const val DEFAULT_SPEED = 0.6
        /** DEFAULT_MINIMAX_VOICE. */
        const val DEFAULT_VOICE = "Chinese (Mandarin)_Radio_Host"
    }
}
