/**
 * The soft music bed under an audio lesson (docs/AUDIO_LESSONS.md "Music"). The lesson MP3 is
 * speech only (the podcast feed too); the players mix the music in themselves, as a second
 * looping track at a low volume: web `AudioLessonPlayerPage` (a second <audio loop>), Lab
 * `LessonMusic` in the background service (a second ExoPlayer). Pure rules here, ported to
 * the Lab app's core (`AudioLessonMusic.kt`, parity-tested).
 *
 * The track is made by `scripts/audio/generate-lesson-music.mjs` (procedural, no samples,
 * no third-party audio — CC0, written for this app): slow, soft pad chords, one loop that
 * breathes out to near silence at its seam, so a player's loop restart is never heard.
 */
import type { AudioLessonFormat } from './types';

export const LESSON_MUSIC = {
  /** Bump the file name when the track changes (the web precache + Lab res/raw follow it). */
  id: 'lesson-music-v1',
  /** Web: served from frontend/public (precached by the PWA, so it plays offline). */
  path: '/audio/lesson-music-v1.mp3',
  /** CC0 1.0 — generated by the repo's own script, no samples. */
  licence: 'CC0-1.0',
} as const;

/** Music on by default: under a sleep lesson yes, under a dialogue lesson no (the learner's choice is remembered per format). */
export function musicDefaultOn(format: AudioLessonFormat | string | null | undefined): boolean {
  return format === 'sleep';
}

/** The music's own volume (0–1, the slider), when the learner hasn't chosen one. Quiet: it sits under the voice. */
export const MUSIC_DEFAULT_VOLUME = 0.35;

/** The slider's range; 0 would be "off" — that is the toggle's job. */
export const MUSIC_MIN_VOLUME = 0.05;
export const MUSIC_MAX_VOLUME = 1;

/** A stored / dragged volume → one the players use (NaN or out of range → the default / clamped, 2 decimals). */
export function parseMusicVolume(raw: unknown): number {
  const v = typeof raw === 'number' ? raw : typeof raw === 'string' && raw.trim() !== '' ? Number(raw) : NaN;
  if (!Number.isFinite(v)) return MUSIC_DEFAULT_VOLUME;
  return Math.round(Math.min(MUSIC_MAX_VOLUME, Math.max(MUSIC_MIN_VOLUME, v)) * 100) / 100;
}

/** A stored on / off ("1" / "0") → the choice, else the format's default. */
export function parseMusicOn(raw: unknown, format: AudioLessonFormat | string | null | undefined): boolean {
  if (raw === '1' || raw === true) return true;
  if (raw === '0' || raw === false) return false;
  return musicDefaultOn(format);
}

/**
 * Whether the music should be playing right now: only while the lesson plays (pause, the end of
 * the lesson and the sleep timer stop it — they pause the lesson) and only when it is on.
 */
export function musicShouldPlay(state: { on: boolean; lessonPlaying: boolean }): boolean {
  return state.on && state.lessonPlaying;
}

/**
 * The music element's volume: the learner's music volume × the sleep timer's fade (1 → 0 over
 * its last 30 s, `sleepFadeVolume`), so the music fades out with the voice. 3 decimals.
 */
export function musicOutputVolume(volume: number, fade = 1): number {
  const v = Math.min(1, Math.max(0, volume)) * Math.min(1, Math.max(0, fade));
  return Math.round(v * 1000) / 1000;
}

/** "Music 35 %" on the slider. */
export function musicVolumeLabel(volume: number): string {
  return `${Math.round(parseMusicVolume(volume) * 100)} %`;
}
