package dev.jeromeswannack.chineselearning.lab.core.calls

/**
 * Port of shared/call-activities/catalogue.ts `ACTIVITY_CATALOGUE`: the bundled in-call activities.
 * CallActivitiesParityTest checks it is exactly the TypeScript list (same ids, same content).
 * The room sends the spec inside every session, so this list only fills the picker.
 */
object ActivityCatalogue {
    val ALL: List<ActivitySpec> = listOf(
        ActivitySpec(
            id = "describe-food-1",
            kind = "describe",
            title = "Describe & guess: food",
            titleZh = "猜一猜：吃的",
            level = "beginner",
            topic = "Food",
            summary = "One sees a food and describes it in Chinese — without saying its name; the other picks it from four.",
            roleNames = RolePair("Describer", "Guesser"),
            tutorRole = "b",
            items = listOf(
                ActivityItem(emoji = "🍎", hanzi = "苹果", pinyin = "píngguǒ", english = "apple", hints = listOf("水果", "红色", "很甜")),
                ActivityItem(emoji = "🍌", hanzi = "香蕉", pinyin = "xiāngjiāo", english = "banana", hints = listOf("黄色", "长长的", "猴子喜欢吃")),
                ActivityItem(emoji = "🍉", hanzi = "西瓜", pinyin = "xīguā", english = "watermelon", hints = listOf("夏天", "很大", "外面是绿色的")),
                ActivityItem(emoji = "🥟", hanzi = "饺子", pinyin = "jiǎozi", english = "dumplings", hints = listOf("春节", "北方人", "里面有肉")),
                ActivityItem(emoji = "🍜", hanzi = "面条", pinyin = "miàntiáo", english = "noodles", hints = listOf("长长的", "用筷子吃", "有汤")),
                ActivityItem(emoji = "🍚", hanzi = "米饭", pinyin = "mǐfàn", english = "cooked rice", hints = listOf("白色的", "每天吃", "一碗")),
                ActivityItem(emoji = "☕", hanzi = "咖啡", pinyin = "kāfēi", english = "coffee", hints = listOf("喝的", "早上", "有点儿苦")),
                ActivityItem(emoji = "🥚", hanzi = "鸡蛋", pinyin = "jīdàn", english = "egg", hints = listOf("早饭", "鸡", "白色的")),
            ),
        ),
        ActivitySpec(
            id = "describe-animals-1",
            kind = "describe",
            title = "Describe & guess: animals",
            titleZh = "猜一猜：动物",
            level = "elementary",
            topic = "Animals",
            summary = "Describe the animal — where it lives, its colour, what it eats, how big it is — and the other guesses.",
            roleNames = RolePair("Describer", "Guesser"),
            tutorRole = "b",
            items = listOf(
                ActivityItem(emoji = "🐼", hanzi = "熊猫", pinyin = "xióngmāo", english = "panda", hints = listOf("黑白", "四川", "吃竹子")),
                ActivityItem(emoji = "🐯", hanzi = "老虎", pinyin = "lǎohǔ", english = "tiger", hints = listOf("很大", "很危险", "黄色和黑色")),
                ActivityItem(emoji = "🐱", hanzi = "猫", pinyin = "māo", english = "cat", hints = listOf("家里", "喜欢鱼", "喵")),
                ActivityItem(emoji = "🐶", hanzi = "狗", pinyin = "gǒu", english = "dog", hints = listOf("人的朋友", "汪汪", "跑得很快")),
                ActivityItem(emoji = "🐰", hanzi = "兔子", pinyin = "tùzi", english = "rabbit", hints = listOf("耳朵很长", "吃胡萝卜", "跳")),
                ActivityItem(emoji = "🐘", hanzi = "大象", pinyin = "dàxiàng", english = "elephant", hints = listOf("非常大", "鼻子很长", "灰色")),
                ActivityItem(emoji = "🐵", hanzi = "猴子", pinyin = "hóuzi", english = "monkey", hints = listOf("树上", "吃香蕉", "很聪明")),
                ActivityItem(emoji = "🐟", hanzi = "鱼", pinyin = "yú", english = "fish", hints = listOf("水里", "游泳", "猫喜欢吃")),
            ),
        ),
        ActivitySpec(
            id = "info-gap-weekend-1",
            kind = "info_gap",
            title = "Information gap: weekend plans",
            titleZh = "周末做什么？",
            level = "elementary",
            topic = "Daily life",
            summary = "Each of you sees half of Xiaoming’s and Xiaohong’s weekend. Ask each other questions to fill in your blanks.",
            roleNames = RolePair("Partner A", "Partner B"),
            tutorRole = "a",
            prompt = "Ask in Chinese, e.g. 小红星期六上午做什么？ — answer with 她…",
            phrases = listOf(
                ActivityWord("小明星期天下午做什么？", "Xiǎo Míng xīngqītiān xiàwǔ zuò shénme?", "What is Xiaoming doing on Sunday afternoon?"),
                ActivityWord("他去打篮球。", "Tā qù dǎ lánqiú.", "He is going to play basketball."),
                ActivityWord("你再说一遍，好吗？", "Nǐ zài shuō yí biàn, hǎo ma?", "Could you say that again?"),
            ),
            columns = listOf("小明", "小红"),
            rows = listOf(
                InfoGapRow("星期六上午", listOf(InfoGapCell("打篮球", "a"), InfoGapCell("去超市", "b"))),
                InfoGapRow("星期六下午", listOf(InfoGapCell("看电影", "b"), InfoGapCell("学中文", "a"))),
                InfoGapRow("星期天上午", listOf(InfoGapCell("睡懒觉", "a"), InfoGapCell("去公园", "b"))),
                InfoGapRow("星期天下午", listOf(InfoGapCell("做饭", "b"), InfoGapCell("见朋友", "a"))),
            ),
            choices = listOf(
                ActivityWord("打篮球", "dǎ lánqiú", "play basketball"),
                ActivityWord("去超市", "qù chāoshì", "go to the supermarket"),
                ActivityWord("看电影", "kàn diànyǐng", "watch a film"),
                ActivityWord("学中文", "xué Zhōngwén", "study Chinese"),
                ActivityWord("睡懒觉", "shuì lǎnjiào", "sleep in"),
                ActivityWord("去公园", "qù gōngyuán", "go to the park"),
                ActivityWord("做饭", "zuò fàn", "cook"),
                ActivityWord("见朋友", "jiàn péngyou", "meet friends"),
                ActivityWord("游泳", "yóuyǒng", "swim"),
                ActivityWord("买衣服", "mǎi yīfu", "buy clothes"),
            ),
        ),
        ActivitySpec(
            id = "roleplay-restaurant-1",
            kind = "roleplay",
            title = "Role-play: ordering in a restaurant",
            titleZh = "在饭馆点菜",
            level = "beginner",
            topic = "Food",
            summary = "A waiter and a customer. Read your lines in turn — tap Done after yours; swap roles and go again.",
            roleNames = RolePair("服务员 Waiter", "客人 Customer"),
            tutorRole = "a",
            setting = "A small dumpling restaurant in Beijing, lunchtime.",
            speakers = RolePair("服务员", "客人"),
            lines = listOf(
                RoleplayLine("a", "你好！请问几位？", "Nǐ hǎo! Qǐngwèn jǐ wèi?", "Hello! How many of you?"),
                RoleplayLine("b", "两位。", "Liǎng wèi.", "Two."),
                RoleplayLine("a", "请坐。这是菜单。", "Qǐng zuò. Zhè shì càidān.", "Please sit down. Here is the menu."),
                RoleplayLine("b", "谢谢。你们有什么好吃的？", "Xièxie. Nǐmen yǒu shénme hǎochī de?", "Thanks. What’s good here?"),
                RoleplayLine("a", "我们的饺子很有名。", "Wǒmen de jiǎozi hěn yǒumíng.", "Our dumplings are famous."),
                RoleplayLine("b", "好，我要一盘饺子和一碗米饭。", "Hǎo, wǒ yào yì pán jiǎozi hé yì wǎn mǐfàn.", "OK, I’d like a plate of dumplings and a bowl of rice."),
                RoleplayLine("a", "喝点儿什么？", "Hē diǎnr shénme?", "Anything to drink?"),
                RoleplayLine("b", "一杯茶，谢谢。", "Yì bēi chá, xièxie.", "A cup of tea, thanks."),
                RoleplayLine("a", "好的，请稍等。", "Hǎo de, qǐng shāo děng.", "Sure, one moment please."),
                RoleplayLine("b", "服务员，买单！", "Fúwùyuán, mǎidān!", "Excuse me — the bill, please!"),
                RoleplayLine("a", "一共八十五块。", "Yígòng bāshíwǔ kuài.", "That’s 85 yuan altogether."),
                RoleplayLine("b", "可以用微信付吗？", "Kěyǐ yòng Wēixìn fù ma?", "Can I pay with WeChat?"),
                RoleplayLine("a", "可以，请扫这里。", "Kěyǐ, qǐng sǎo zhèlǐ.", "Yes — please scan here."),
            ),
        ),
        ActivitySpec(
            id = "roleplay-directions-1",
            kind = "roleplay",
            title = "Role-play: asking the way",
            titleZh = "问路",
            level = "elementary",
            topic = "Travel",
            summary = "A tourist asks a passer-by for the subway station. Read your part; swap and try again without looking at the pinyin.",
            roleNames = RolePair("路人 Passer-by", "游客 Tourist"),
            tutorRole = "a",
            setting = "A busy street corner in Shanghai.",
            speakers = RolePair("路人", "游客"),
            lines = listOf(
                RoleplayLine("b", "不好意思，请问地铁站在哪儿？", "Bù hǎoyìsi, qǐngwèn dìtiězhàn zài nǎr?", "Excuse me, where is the subway station?"),
                RoleplayLine("a", "一直往前走，到第二个路口往右拐。", "Yìzhí wǎng qián zǒu, dào dì-èr gè lùkǒu wǎng yòu guǎi.", "Go straight ahead and turn right at the second crossing."),
                RoleplayLine("b", "远不远？", "Yuǎn bu yuǎn?", "Is it far?"),
                RoleplayLine("a", "不太远，走路大概十分钟。", "Bú tài yuǎn, zǒulù dàgài shí fēnzhōng.", "Not too far — about ten minutes on foot."),
                RoleplayLine("b", "地铁站旁边有银行吗？", "Dìtiězhàn pángbiān yǒu yínháng ma?", "Is there a bank near the station?"),
                RoleplayLine("a", "有，银行就在地铁站对面。", "Yǒu, yínháng jiù zài dìtiězhàn duìmiàn.", "Yes, the bank is right across from the station."),
                RoleplayLine("b", "太好了，谢谢你！", "Tài hǎo le, xièxie nǐ!", "Great, thank you!"),
                RoleplayLine("a", "不客气。", "Bú kèqi.", "You’re welcome."),
            ),
        ),
        ActivitySpec(
            id = "build-sentences-1",
            kind = "build",
            title = "Build the sentence together",
            titleZh = "一起连词成句",
            level = "elementary",
            topic = "Grammar: 把, 比, 过, 了",
            summary = "Scrambled words on a shared board — either of you taps them into order. The tutor reveals the answer; then both say it aloud.",
            roleNames = RolePair("Builder", "Builder"),
            tutorRole = "a",
            items = listOf(
                ActivityItem(tiles = listOf("我", "把", "书", "放在", "桌子上"), pinyin = "Wǒ bǎ shū fàng zài zhuōzi shang.", english = "I put the book on the table."),
                ActivityItem(tiles = listOf("他", "昨天", "去", "北京", "了"), pinyin = "Tā zuótiān qù Běijīng le.", english = "He went to Beijing yesterday."),
                ActivityItem(tiles = listOf("你", "吃过", "北京烤鸭", "吗"), pinyin = "Nǐ chīguo Běijīng kǎoyā ma?", english = "Have you ever had Peking duck?"),
                ActivityItem(tiles = listOf("我", "比", "我哥哥", "高"), pinyin = "Wǒ bǐ wǒ gēge gāo.", english = "I am taller than my older brother."),
                ActivityItem(tiles = listOf("请", "把", "门", "关上"), pinyin = "Qǐng bǎ mén guānshang.", english = "Please close the door."),
                ActivityItem(tiles = listOf("我们", "一起", "去", "看", "电影", "吧"), pinyin = "Wǒmen yìqǐ qù kàn diànyǐng ba.", english = "Let’s go and see a film together."),
            ),
        ),
        ActivitySpec(
            id = "quiz-tones-1",
            kind = "quiz",
            title = "Quick quiz: which one did you hear?",
            titleZh = "听一听：哪一个？",
            level = "beginner",
            topic = "Listening: tones",
            summary = "The tutor plays a word (it plays on both devices, text hidden); the student picks what they heard; the tutor marks it.",
            roleNames = RolePair("Asker", "Answerer"),
            tutorRole = "a",
            questions = listOf(
                QuizQuestion(prompt = "", audio = "买", options = listOf("mǎi 买 (buy)", "mài 卖 (sell)"), answer = 0, explanation = "买 mǎi is the 3rd tone (dips); 卖 mài the 4th (falls)."),
                QuizQuestion(prompt = "", audio = "卖", options = listOf("mǎi 买 (buy)", "mài 卖 (sell)"), answer = 1, explanation = "卖 mài falls sharply — 4th tone."),
                QuizQuestion(prompt = "", audio = "糖", options = listOf("tāng 汤 (soup)", "táng 糖 (sugar)"), answer = 1, explanation = "糖 táng rises (2nd tone); 汤 tāng stays high (1st)."),
                QuizQuestion(prompt = "", audio = "又", options = listOf("yǒu 有 (to have)", "yòu 又 (again)"), answer = 1, explanation = "又 yòu falls (4th); 有 yǒu dips (3rd)."),
                QuizQuestion(prompt = "", audio = "马", options = listOf("mā 妈 (mum)", "mǎ 马 (horse)"), answer = 1, explanation = "马 mǎ dips; 妈 mā is high and level."),
                QuizQuestion(prompt = "", audio = "水饺", options = listOf("shuìjiào 睡觉 (sleep)", "shuǐjiǎo 水饺 (dumplings)"), answer = 1, explanation = "水饺 shuǐjiǎo: two 3rd tones — the first one is said as a 2nd."),
                QuizQuestion(prompt = "", audio = "请问", options = listOf("qǐngwèn 请问 (excuse me)", "qīnwěn 亲吻 (to kiss)"), answer = 0, explanation = "Get this one right in a shop: 请问 qǐngwèn = excuse me, may I ask."),
            ),
        ),
        ActivitySpec(
            id = "quiz-measure-words-1",
            kind = "quiz",
            title = "Quick quiz: measure words",
            titleZh = "量词小测验",
            level = "elementary",
            topic = "Grammar: measure words",
            summary = "The tutor pushes a question; the student picks the measure word (and says the phrase aloud); the tutor sees the pick live and marks it.",
            roleNames = RolePair("Asker", "Answerer"),
            tutorRole = "a",
            questions = listOf(
                QuizQuestion(prompt = "一___书 (a book)", options = listOf("本", "个", "张", "条"), answer = 0, explanation = "本 běn for books and notebooks."),
                QuizQuestion(prompt = "一___纸 (a sheet of paper)", options = listOf("本", "张", "条", "只"), answer = 1, explanation = "张 zhāng for flat things: paper, tables, tickets, photos."),
                QuizQuestion(prompt = "一___鱼 (a fish)", options = listOf("只", "张", "条", "件"), answer = 2, explanation = "条 tiáo for long, thin things: fish, roads, rivers, trousers."),
                QuizQuestion(prompt = "一___猫 (a cat)", options = listOf("条", "只", "个", "本"), answer = 1, explanation = "只 zhī for most animals (and one of a pair)."),
                QuizQuestion(prompt = "三___衣服 (three items of clothing)", options = listOf("条", "张", "件", "杯"), answer = 2, explanation = "件 jiàn for clothes (on the upper body) and matters."),
                QuizQuestion(prompt = "一___咖啡 (a cup of coffee)", options = listOf("杯", "本", "只", "件"), answer = 0, explanation = "杯 bēi = a cup / glass of something."),
            ),
        ),
        ActivitySpec(
            id = "dictation-everyday-1",
            kind = "dictation",
            title = "Dictation: everyday words",
            titleZh = "听写：常用词",
            level = "beginner",
            topic = "Everyday words",
            summary = "The tutor says a word (or plays it); the student types it in characters; the tutor watches it being typed and marks it.",
            roleNames = RolePair("Reader", "Writer"),
            tutorRole = "a",
            items = listOf(
                ActivityItem(hanzi = "你好", pinyin = "nǐ hǎo", english = "hello"),
                ActivityItem(hanzi = "谢谢", pinyin = "xièxie", english = "thank you"),
                ActivityItem(hanzi = "朋友", pinyin = "péngyou", english = "friend"),
                ActivityItem(hanzi = "老师", pinyin = "lǎoshī", english = "teacher"),
                ActivityItem(hanzi = "喜欢", pinyin = "xǐhuan", english = "to like"),
                ActivityItem(hanzi = "今天", pinyin = "jīntiān", english = "today"),
                ActivityItem(hanzi = "明天", pinyin = "míngtiān", english = "tomorrow"),
                ActivityItem(hanzi = "吃饭", pinyin = "chī fàn", english = "to eat (a meal)"),
            ),
        ),
    )
}
