#!/usr/bin/env node
/**
 * Embeds the built HTML file into a TypeScript module
 * so it can be imported by the Cloudflare Worker
 */
import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const distDir = join(__dirname, '..', 'dist');
const srcDir = join(__dirname, '..', 'src');

const htmlPath = join(distDir, 'index.html');
const outputPath = join(srcDir, 'study-app-html.ts');

try {
  const html = readFileSync(htmlPath, 'utf-8');

  // Escape backticks and ${} in the HTML for template literal
  const escapedHtml = html
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');

  const output = `// This file is auto-generated by scripts/embed-html.js
// Do not edit directly - run \`npm run build:ui\` to regenerate

export const STUDY_APP_HTML = \`${escapedHtml}\`;
`;

  writeFileSync(outputPath, output);
  console.log('✓ Embedded HTML into src/study-app-html.ts');
} catch (err) {
  console.error('Error embedding HTML:', err.message);
  process.exit(1);
}
