#!/usr/bin/env node
/**
 * Embeds the built single-file HTML of every MCP App into a TypeScript
 * module so the Cloudflare Worker can serve them as ui:// resources.
 *
 *   node scripts/embed-html.js study students_dashboard ...
 *
 * reads dist/<name>/index.html for each name and writes src/app-html.ts.
 */
import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const distDir = join(__dirname, '..', 'dist');
const srcDir = join(__dirname, '..', 'src');
const outputPath = join(srcDir, 'app-html.ts');

const names = process.argv.slice(2);
if (names.length === 0) {
  console.error('usage: embed-html.js <app name>...');
  process.exit(1);
}

const escape = (html) => html.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

try {
  const entries = names.map((name) => {
    const html = readFileSync(join(distDir, name, 'index.html'), 'utf-8');
    return `  ${JSON.stringify(name)}: \`${escape(html)}\`,`;
  });
  const output = `// This file is auto-generated by scripts/build-apps.mjs (via embed-html.js)
// Do not edit directly - run \`npm run build:ui\` to regenerate

/** Single-file HTML of every MCP App, keyed by app name. */
export const APP_HTML: Record<string, string> = {
${entries.join('\n')}
};

/** The original flashcard study app. */
export const STUDY_APP_HTML = APP_HTML["study"];
`;
  writeFileSync(outputPath, output);
  console.log(`✓ Embedded ${names.length} app(s) into src/app-html.ts: ${names.join(', ')}`);
} catch (err) {
  console.error('Error embedding HTML:', err.message);
  process.exit(1);
}
